#1번
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY,
	BOOK_NAME VARCHAR(10) NOT NULL,
	WRITER VARCHAR(10) NOT NULL,
	PRICE INT,
	PUBLISHER VARCHAR(10) DEFAULT '미지정',
	PUB_DATE DATE
);

#2번
INSERT INTO book_info(BOOK_NUM,BOOK_NAME,WRITER,PRICE,PUBLISHER,PUB_DATE)
VALUES(101,'자바 기초', '홍길동', 30000, 'A출판', 20250215);

INSERT INTO book_info(BOOK_NUM,BOOK_NAME,WRITER,PRICE,PUBLISHER,PUB_DATE)
VALUES(102,'리액트 기초', '이순신', 20000, 'B출판', 20250122);

#3번
UPDATE book_info
SET
	BOOK_NAME = '자바_고급',
	PRICE = 25000,
	PUBLISHER = 'IT출판'
WHERE BOOK_NUM = 101;

#EMP,DEPT테이블 문제
#4번
SELECT EMPNO,ENAME,SAL,COMM 인센티브
FROM emp
WHERE SAL BETWEEN 500 AND 3000 AND COMM IS NULL;

#5번
SELECT EMPNO,ENAME,JOB,HIREDATE
FROM emp
WHERE ENAME LIKE '%병%' OR ENAME LIKE '%김%'
ORDER BY JOB ASC, EMPNO DESC;

#6번
SELECT
	EMPNO,
	ENAME,
	DEPTNO,
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END AS 부서명
FROM emp;

#7번
SELECT EMPNO,ENAME,TO_CHAR(HIREDATE, 'YYYY.MM.DD HH24.MI.SS')
FROM emp
WHERE MOD(MONTH(HIREDATE),2)=0
AND JOB IN('사원','과장','차장')
ORDER BY HIREDATE ASC;

#8번
SELECT EMPNO,ENAME,SAL,COMM,
		(SAL * 12) + IFNULL(COMM,0) AS TOTAL_SALARY
FROM emp
ORDER BY SAL DESC;		

#9번
SELECT EMPNO,DEPTNO,SUBSTR(ENAME,2) AS 이름
FROM emp
WHERE YEAR(HIREDATE) BETWEEN 2003 AND 2006;

#10번
조회되는 행의 갯수 : 3개
