CREATE TABLE CAR_INFO(
	CAR_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CAR_NAME VARCHAR(20) NOT NULL,
	PRICE INT NOT NULL,
	MAKER VARCHAR(20) NOT NULL
);

CREATE TABLE SALES_INFO(
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT,
	BUYER VARCHAR(20) NOT NULL,
	PHONE VARCHAR(20),
	COLOR VARCHAR(20) NOT NULL,
	SALE_DATE DATETIME DEFAULT SYSDATE(),
	CAR_NUM INT REFERENCES CAR_INFO(CAR_NUM)
);

SELECT * FROM CAR_INFO;
SELECT * FROM sales_info;

SELECT
	SALES_NUM,
	CAR_NUM
FROM sales_info;

SELECT 
	BUYER,
	PHONE,
	SALE_DATE,
	COLOR,
	(SELECT CAR_NAME
	FROM CAR_INFO
	WHERE CAR_NUM = sales_info.CAR_NUM) CAR_NAME,
	(SELECT PRICE
	FROM CAR_INFO
	WHERE CAR_NUM = sales_info.CAR_NUM) PRICE
FROM sales_info	
ORDER BY SALE_DATE DESC;