 CREATE TABLE BASIC_BOARD (
	 BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT  #컬럼의값을지정하지않으면자동으로1씩증가된값을넣어주는기능을한다.
	 , TITLE VARCHAR(30)
	 , WRITER VARCHAR(20)
	 , CONTENT VARCHAR(50)
	 , READ_CNT INT DEFAULT 0
	 , CREATE_DATE DATETIME DEFAULT SYSDATE()
 );
 
 SELECT * FROM basic_board;
 
 INSERT INTO basic_board (TITLE, WRITER, CONTENT) VALUES ('제목1', '작성자1', '내용1');
 INSERT INTO basic_board (TITLE, WRITER, CONTENT) VALUES ('제목2', '작성자2', '내용2');
 INSERT INTO basic_board (TITLE, WRITER, CONTENT) VALUES ('제목3', '작성자3', '내용3');
 COMMIT;
 
 # 데이터에 변화가 생기는 쿼리문(insert, delete, update)을 실행하면 commit or rollback;
 
 
 #회원 정보 테이블
 CREATE TABLE BASIC_MEMBER(
 	MEM_ID VARCHAR(20) PRIMARY KEY,
 	MEM_PW VARCHAR(20) NOT NULL,
 	MEM_NAME VARCHAR(10),
 	MEM_AGE INT,
 	BIRTHDAY DATETIME
 );
 
 SELECT * FROM basic_member;
 
 COMMIT;
 
 DELETE FROM BASIC_MEMBER
 WHERE MEM_ID = 'KIM';
 
SELECT 
	MEM_ID,
	MEM_PW,
	MEM_NAME,
	MEM_AGE,
	BIRTHDAY
FROM basic_member
WHERE MEM_ID = 'java';

SELECT MEM_ID, 
		MEM_NAME,
		MEM_AGE
FROM basic_member;

SELECT
	BOARD_NUM, 
	TITLE,
	WRITER,
	CREATE_DATE,
	READ_CNT
FROM basic_board
WHERE TITLE LIKE '%제%';	