CREATE TABLE MY_MEMBER(
	NUM INT PRIMARY KEY,
	ID VARCHAR(20) NOT NULL,
	PW VARCHAR(20) NOT NULL,
	NAME VARCHAR(10) NOT NULL,
	AGE INT,
	EMAIL VARCHAR(20) UNIQUE
);

COMMIT;

SELECT * FROM my_member;

DROP TABLE my_member;

INSERT INTO my_member(NUM,ID,PW,NAME,AGE,EMAIL)
VALUES(101,'KIM','1234','김자바',30,'kim@gmail.com');

INSERT INTO my_member(NUM,ID,PW,NAME,AGE,EMAIL)
VALUES(102,'HONG','5678','홍자바',25,'hong@gmail.com');

UPDATE my_member
SET
	NAME = '유관순',
	AGE = AGE + 5
WHERE NUM=101;

SELECT * FROM emp;

SELECT EMPNO,ENAME,SAL,COMM
FROM emp
WHERE SAL BETWEEN 500 AND 3000 AND COMM IS NOT NULL;

SELECT EMPNO,ENAME,HIREDATE
FROM emp
WHERE ENAME LIKE '%기' OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

SELECT
	EMPNO,
	ENAME,
	DEPTNO,
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END
FROM emp;

SELECT 
	EMPNO, 
	ENAME, 
	HIREDATE, 
	IFNULL(COMM,0)
FROM emp
WHERE MONTH(HIREDATE)=1
ORDER BY HIREDATE ASC;

