
#게시판 프로젝트 테이블
CREATE TABLE BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(30) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(50),
	READ_CNT INT DEFAULT 0,
	CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM board;
COMMIT;

DROP TABLE board;

INSERT INTO BOARD(TITLE, WRITER, CONTENT, READ_CNT)
VALUES('제목4', '작성자4', '내용4입니다', 5);


#상품 정보 테이블
CREATE TABLE ITEM(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT,
	ITEM_CATEGORY VARCHAR(30) NOT NULL,
	ITEM_NAME VARCHAR(20) NOT NULL UNIQUE,
	ITEM_PRICE INT NOT NULL,
	ITEM_INTRO VARCHAR(50),
	ITEM_STATUS VARCHAR(10), #상품준비중, 판매중, 매진
	REG_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM item;

INSERT INTO item(ITEM_CATEGORY,ITEM_NAME,ITEM_PRICE,ITEM_INTRO,ITEM_STATUS)
VALUES('하의','청바지',5000,'상품소개3','판매중');

SELECT SUM(ITEM_PRICE) FROM item;