CREATE TABLE BOOK(
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT,
	BOOK_NAME VARCHAR(10) NOT NULL UNIQUE,
	CATEGORY VARCHAR(10) NOT NULL,
	WRITER VARCHAR(10) NOT NULL,
	PRICE INT,
	PUBLICATION_DATE DATETIME DEFAULT SYSDATE(),
	RENTAL_CNT INT
);

INSERT INTO book (BOOK_NAME, CATEGORY, WRITER, PRICE, RENTAL_CNT)
VALUES ('직장인 월급관리', '자기계발', '윤여행', 13000, 8);

SELECT * FROM BOOK;

UPDATE BOOK
SET
	PRICE =  PRICE + 1000,
	RENTAL_CNT = RENTAL_CNT + 5
WHERE WRITER = '윤여행';

COMMIT;